############
#
# Caches
#
# Caches may require a prefix, since caches in CircleCI 2.0 are immutable.
# A prefix provides an easy way to invalidate a cache.  See https://circleci.com/docs/2.0/caching/#clearing-cache
#
############

version: 2.1

executors:
  primary:
    docker:
      - image: cimg/base:2022.06
  python_test:
    docker:
      - image: cimg/python:3.7
  pre_commit_test:
    docker:
      - image: cimg/python:3.7

jobs:

  # `build` is used for building the archive
  build:
    executor: primary
    working_directory: ~/src
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run:
          name: Build
          command: |
            make archive
            ls -l build

  # `pre_commit_deps` is used for cache pre-commit sources
  pre_commit_deps:
    executor: pre_commit_test
    steps:
      - checkout

      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run: pip install pre-commit==2.21.0
      - run: pre-commit install-hooks

      - save_cache:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit

  # `pre_commit_test` is used to run pre-commit hooks on all files
  pre_commit_test:
    executor: pre_commit_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run: pip install pre-commit==2.21.0
      - run:
          name: Run pre-commit tests
          command: pre-commit run --all-files

  # `test` is used to run python tests
  test:
    executor: python_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-dev.txt
      - run: nosetests

workflows:
  main:
    jobs:
      - pre_commit_deps
      - pre_commit_test:
          requires:
            - pre_commit_deps
      - test
      - build:
          requires:
            - pre_commit_test
            - test
